### ISSUE TITLE
Binding objects don't seem to work

### ISSUE THREAD

**Issue by gazal-k** [grappendorf/grapp-template-ref#1]
The following block doesn't display 'value'.

``` html
<template is="dom-template" id="template-bind"><span>[[key]]</span></template>
<grapp-template-ref ref="template-bind" id="template-bind-ref" bind='{"key":"value"}'></grapp-template-ref>
```

Tried running the given tests, which produces the following result:

``` sh
Running "shell:test" (shell) task
Running "wct-test" task
Starting Selenium server for local browsers
Selenium server running on port 43043
Web server running on port 2000 and serving from /home/gazal/git/grapp-template-ref
chrome 44                Beginning tests via http://localhost:2000/components/grapp-template-ref/generated-index.html?cli_browser_id=0
404 GET /components/grapp-template-ref/build/grapp-template-ref.html
chrome 44                ✖ test/basic.html » template stamping » should instantiate the template dom

  expected undefined to equal 'the template content'
    <unknown> at   Context.eval at coffeescript:6:0

chrome 44                ✖ test/basic.html » template binding » should bind the template to the specified object

  expected undefined to equal 'value'
    <unknown> at   Context.eval at coffeescript:14:0

chrome 44                Tests failed: 2 failed tests
Test run ended in failure: 2 failed tests

chrome 44 (0/0/2)                     

```

**Comment by grappendorf** [comment]
Thanks for your feedback. But just use https://github.com/Trakkasure/dom-bindref. Brandon has done some more effort to get this working, so i will use his component in my own projects too (and discard my own component).

**Comment by grappendorf** [comment]
Ok, not quite yet. Because of the special use-case i am working on (i am copying a template that i will refer to into another DOM location), _dom-bindref_ is currently not working for me.

First: Brandon is using _stamp(this.bind)_ to bind the scope object (as was i) and this is why my use-case and the example above are not working (oddly enough: for me the test works. Only when i put the example into the `template is="dom-bind"` in the index.html, it fails.)  Calling the template constructor with `new template.ctor(bind, template)` instead seems to work.

Second: If the bind object contains special keys like _id_, i get an _invalid invocation error_ in Polymers `_applyConfig()` function when calling either `stamp()` or the constructor. So i added a new _as_ property. When _as_ is specified, the template scope is a hash containing the bind object under the key _as_.

**Comment by grappendorf** [comment]
Maybe this is fixed in the [latest version 0.1.0](https://github.com/grappendorf/grapp-template-ref/tree/0.1.0)

**Comment by gazal-k** [comment]
I also added a new `as` property. Check my changes here: https://github.com/Polymer/polymer/pull/2196. I'm in writing tests for it at the moment.

**Comment by gazal-k** [comment]
@grappendorf please check and give any feedback you may have.
